#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook 'build-essential'
cookbook 'apt'
cookbook 'openssl' 
cookbook 'mysql'
cookbook 'database'
cookbook 'nginx'
cookbook 'git' 
cookbook 'rvm', :git => "https://github.com/fnichol/chef-rvm"
cookbook 'nodejs'
cookbook 'unicorn'